[package]
name = "ad-hoc-iterator"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Create an ad-hoc iterator."
repository = "https://github.com/Garbaz/ad_hoc_iterator"


[dependencies]
