[package]
name = "ad-hoc-iterator"
version = "0.2.2"
edition = "2021"
license = "MIT"
description = "Create an ad-hoc iterator."
repository = "https://github.com/Garbaz/ad-hoc-iterator"


[dependencies]
